# Project name
spring.application.name=ExaminationSystem

# PostgreSQL DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/new_data
spring.datasource.username=postgres
spring.datasource.password=@Abhay-1424
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate auto schema update (use with caution in production)
spring.jpa.hibernate.ddl-auto=update

# Prevent circular reference errors (needed if you have bi-directional dependencies)
spring.main.allow-circular-references=true

# Hibernate dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL queries in console
spring.jpa.show-sql=true

# Server port
server.port=8181
